In [29]:
import numpy as np

In [30]:
n, b = tuple(map(lambda x: int(x), input().split()))

2 5


In [31]:
mat = []
for i in range(n):
    mat.append(list(map(lambda x: int(x), input().split())))

1 2
3 4


In [32]:
mat = np.array(mat)

In [33]:
mat

array([[1, 2],
       [3, 4]])

In [34]:
mat @ mat

array([[ 7, 10],
       [15, 22]])

In [61]:
result = np.eye(n) # 단위 행렬
sum_value = np.zeros((n, n))
sum_value
for i in range(b):
    result = result @ mat
    sum_value = (sum_value + result) % 1000

In [71]:
# astype 메소드는 dtype을 변환한 값을 "반환", 받을 변수가 존재해야 함!
sum_value = sum_value.astype(np.int32)

In [74]:
sum_value

array([[313, 914],
       [871, 184]], dtype=int32)

In [73]:
for i in sum_value:
    for j in i:
        print(j, end=" ")
    print()

313 914 
871 184 
