In [ ]:
# runtime error,,

In [1]:
import numpy as np

In [2]:
# 정수값으로 입력 개수 num, 입력의 길이 length를 받기
# 입력 범위: 3<=num<=1000, 
num, length = tuple(input().split())

5 3


In [3]:
num, length = int(num), int(length)

In [4]:
binaryCode = [input() for i in range(5)]

000
111
010
110
001


In [5]:
start, end = tuple(map(lambda x: int(x), input().split()))

1 2


In [6]:
# 문자열 형태로 각각의 입력값이 저장된 ndarray
binaryCode

['000', '111', '010', '110', '001']

In [7]:
# 해밍 경로 여부 찾는 함수 (참:1, 거짓:0)
def isHR(str1, str2, length):
    cnt = 0 # cnt: 두 문자열(str1, str2)의 해밍 거리

    # 비교하는 값이 자기 자신이면 0 리턴 (자기 자신과는 해밍 경로 고려 X)
    if str1 is str2: return 0

    for i in range(length):
        if str1[i] is not str2[i]: cnt+=1
        if cnt > 1: return 0    # 해밍 거리가 2 이상이면 해밍 경로가 아님(0)
    return 1

In [8]:
checkHR = np.zeros((num, num))

In [9]:
checkHR

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
for i in range(num):
    for j in range(num):
        checkHR[i][j] = isHR(binaryCode[i], binaryCode[j], length)

In [11]:
checkHR

array([[0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [12]:
visit = np.zeros(num)

In [13]:
visit

array([0., 0., 0., 0., 0.])

In [14]:
def findRoutine(pos, en, checkHR, visit):
    visit[pos]=1 # 방문한 인덱스는 1로 변경
#    print("pos:",pos, "  ")
    if pos==en:
        print(pos+1, end=" ")
        return True
    for i, val in enumerate(checkHR[pos]):
#        print("val:",val,"i:",i,"visit[i]",visit[i], end=" ")
        if val == 1 and visit[i]==0 :
#            print(i, end="")
            if findRoutine(i, en, checkHR, visit):
                print(pos+1, end=" ")
                return True
#        print()
    return False

In [15]:
findRoutine(end-1, start-1, checkHR, visit)

1 3 4 2 

True